site_name: Orwynn
site_url: https://orwynn.ryzhovalex.com
repo_url: https://github.com/ryzhovalex/orwynn
site_author: Alexander Ryzhov
copyright: Alexander Ryzhov @2023

theme:
    name: "material"

plugins:
    - search
    - autorefs
    - mkdocstrings:
        handlers:
            python:
                options:
                    show_source: false
                    show_root_toc_entry: false

nav:
    - Introduction: index.md
    - Overview:
        - Getting Started: GettingStarted.md
    - API Reference: APIReference.md
