[tool.poetry]
name = "orwynn"
version = "0.1.0"
description = "Structured backend web-framework built on top of FastAPI"
authors = ["ryzhovalex <thed4rkof@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.88.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
loguru = "^0.6.0"
pyyaml = "^6.0"
pytest = "^7.2.0"
pyjwt = "^2.6.0"
httpx = "^0.23.1"

[tool.pytest.ini_options]
testpaths = [
  "orwynn",
  "tests"
]
pythonpath = [
  "orwynn"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
